"""
This type stub file was generated by pyright.
"""

class date_class:
    def __init__(self) -> None:
        ...
    
    def date_form(self, input_form=..., output_form=...): # -> None:
        ...
    
    def set_time0(self, string, input_form=...): # -> None:
        ...
    
    def today_datetime(self): # -> datetime:
        ...
    
    def today_string(self, output_form=...): # -> str:
        ...
    
    def datetime_to_string(self, datetime, output_form=...):
        ...
    
    def datetimes_to_strings(self, datetimes, output_form=...): # -> list[Any]:
        ...
    
    def string_to_datetime(self, string, input_form=...): # -> datetime:
        ...
    
    def correct_form(self, date_form): # -> LiteralString:
        ...
    
    def string_to_time(self, string, input_form=..., time0=...): # -> float:
        ...
    
    def strings_to_time(self, strings, input_form=...): # -> list[float | Any]:
        ...
    
    def time_to_string(self, time, output_form=...): # -> str:
        ...
    
    def times_to_string(self, times, input_form=...): # -> list[str]:
        ...
    


