"""
This type stub file was generated by pyright.
"""

class default_figure_class:
    def __init__(self) -> None:
        ...
    
    def set_limitsize(self, limit_width=..., limit_height=...): # -> None:
        ...
    
    def set_size_term(self, width=..., height=...): # -> None:
        ...
    
    def set_size_term_inf(self, width=..., height=...): # -> None:
        ...
    


class default_monitor_class:
    def __init__(self) -> None:
        ...
    
    def color_init(self): # -> None:
        ...
    
    def axes_init(self): # -> None:
        ...
    
    def canvas_init(self): # -> None:
        ...
    
    def text_init(self): # -> None:
        ...
    
    def draw_init(self): # -> None:
        ...
    
    def bar_init(self): # -> None:
        ...
    
    def confusion_matrix_init(self): # -> None:
        ...
    


