"""
This type stub file was generated by pyright.
"""

class CandlestickChart:
    def __init__(
        self, timeframe: str = ..., max_candles: int = ..., refresh_rate: float = ...
    ) -> None:
        """
        Initializes the real-time candlestick chart.

        :param timeframe: The candle timeframe (e.g., "15m"). Currently supports minutes (e.g., "15m").
        :param max_candles: Maximum number of candles to display.
        :param refresh_rate: How frequently (in seconds) to update the chart.
        """
        ...

    def update_ohlcv(self, ohlcv: list[float]) -> None:
        """
        Updates the internal state with new OHLCV data.

        The expected format for ohlcv is:
          [timestamp, open, high, low, close, volume]
        where timestamp is in milliseconds.
        """
        ...

    def stop(self) -> None:
        """
        Stops the background refresh thread.
        """
        ...

if __name__ == "__main__":
    chart = ...
