"""
This type stub file was generated by pyright.
"""

from ccxt.abstract.bequant import ImplicitAPI
from ccxt.async_support.hitbtc import hitbtc

class bequant(hitbtc, ImplicitAPI):
    def describe(self):  # -> dict[Any, Any] | None:
        ...
