"""
This type stub file was generated by pyright.
"""

from ccxt.abstract.binanceus import ImplicitAPI
from ccxt.async_support.binance import binance

class binanceus(binance, ImplicitAPI):
    def describe(self):  # -> dict[Any, Any] | None:
        ...
