"""
This type stub file was generated by pyright.
"""

from ccxt.abstract.bitpanda import ImplicitAPI
from ccxt.async_support.onetrading import onetrading

class bitpanda(onetrading, ImplicitAPI):
    def describe(self):  # -> dict[Any, Any] | None:
        ...
