"""
This type stub file was generated by pyright.
"""

from ccxt.abstract.myokx import ImplicitAPI
from ccxt.async_support.okx import okx

class myokx(okx, ImplicitAPI):
    def describe(self):  # -> dict[Any, Any] | None:
        ...
