"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass

from ccxt.base.exchange import Exchange

@dataclass
class Position:
    symbol: str
    direction: str
    size: float
    funding_time: str
    ...

open_positions: dict[str, Position] = ...

async def robust_fetch_balance(exchange: Exchange) -> float:
    """
    Fetches the free balance for USDT with retry logic.
    """
    ...

async def try_open_position(exchange: Exchange, symbol: str, direction: str) -> None:
    """
    Opens a position using a market order.
    """
    ...

async def close_position(exchange: Exchange, symbol: str) -> None:
    """
    Closes an open position with a market order.
    """
    ...
