"""
This type stub file was generated by pyright.
"""

from typing import Any, Callable

class FundingRateArbitrage:
    def __init__(
        self,
        exchanges_config: list[dict[str, Any]],
        initialize_exchange: Callable[..., Any],
        start_balance_manager: Callable[..., Any],
        funding_rate_collector: Callable[..., Any],
        funding_rate_analyzer: Callable[..., Any],
        top_opportunities: int,
    ) -> None:
        """
        Initializes the FundingRateArbitrage class with dependencies injected.

        Args:
            exchanges_config: List of exchange configurations.
            initialize_exchange: Function to initialize an exchange.
            start_balance_manager: Function to start balance management.
            funding_rate_collector: Function to collect funding rates.
            funding_rate_analyzer: Function to analyze funding rates.
            top_opportunities: Number of top swap markets to monitor.
        """
        ...

    async def run(self) -> None:
        """
        Asynchronously orchestrates funding rate arbitrage across multiple exchanges.
        """
        ...

if __name__ == "__main__":
    async def mock_initialize_exchange(
        exchange_id: str, api_key: str, api_secret: str, api_password: str = ...
    ):  # -> MockExchange:
        class MockExchange:
            class MockSession: ...

    async def mock_start_balance_manager(config: list[dict[str, str]]):  # -> None:
        ...
    async def mock_funding_rate_collector(exchange: Any, market: str):  # -> None:
        ...
    async def mock_funding_rate_analyzer():  # -> None:
        ...

    exchanges_config = ...
    arbitrage = ...
