"""
This type stub file was generated by pyright.
"""

from typing import Any, Dict

async def funding_rate_arbitrage(exchanges_config: list[Dict[str, Any]]) -> None:
    """
    Initializes multiple exchanges, starts funding rate collectors, and runs arbitrage strategy.
    """
    ...

