"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from datetime import datetime
from decimal import Decimal

from ccxt.base.exchange import Exchange

@dataclass
class FundingRate:
    exchange: str
    symbol: str
    funding_rate: Decimal
    timestamp: datetime
    ...

@dataclass
class Position:
    long_exchange: str
    short_exchange: str
    symbol: str
    funding_time: datetime
    ...

class FundingRateManager:
    def __init__(self, check_interval: int) -> None: ...
    async def collect_funding_rate(self, exchange: Exchange, market: str) -> None:
        """Collects funding rates from a specific exchange."""
        ...

    async def analyze_funding_rates(self) -> None:
        """Analyzes funding rates to find arbitrage opportunities."""
        ...
