"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from decimal import Decimal
from typing import Any

from ccxt.base.exchange import Exchange

@dataclass
class Position:
    symbol: str
    direction: str
    size: float
    funding_time: str
    ...

open_positions: dict[str, Position] = ...

async def fetch_balance(exchange: Any, currency: str) -> Decimal:
    """Fetches balance from the given exchange."""
    ...

async def close_position(exchange: Exchange, symbol: str) -> None:
    """
    Closes an open position with a market order.
    """
    ...

async def transfer_funds(
    source_exchange: Exchange, dest_exchange: Exchange, currency: str, amount: Decimal
) -> bool:
    """
    Transfers funds from one exchange to another.

    Args:
        source_exchange (Exchange): The exchange to withdraw from.
        dest_exchange (Exchange): The exchange to deposit to.
        currency (str): The currency to transfer.
        amount (Decimal): The amount to transfer.

    Returns:
        bool: True if transfer was initiated successfully, False otherwise.
    """
    ...
