"""
This type stub file was generated by pyright.
"""

class OkxAPIException(Exception):
    def __init__(self, response) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    


class OkxRequestException(Exception):
    def __init__(self, message) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    


class OkxParamsException(Exception):
    def __init__(self, message) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    


