"""
This type stub file was generated by pyright.
"""

def sign(message, secretKey): # -> bytes:
    ...

def pre_hash(timestamp, method, request_path, body, debug=...):
    ...

def get_header(api_key, sign, timestamp, passphrase, flag, debug=...): # -> dict[Any, Any]:
    ...

def get_header_no_sign(flag, debug=...): # -> dict[Any, Any]:
    ...

def parse_params_to_str(params): # -> str:
    ...

def get_timestamp(): # -> str:
    ...

def signature(timestamp, method, request_path, body, secret_key): # -> bytes:
    ...

