"""
This type stub file was generated by pyright.
"""

from ccxt.pro.coinbase import coinbase

class coinbaseadvanced(coinbase):
    def describe(self): # -> dict[Any, Any] | None:
        ...
    


