"""
This type stub file was generated by pyright.
"""

from typing import List

import ccxt.async_support
from ccxt.async_support.base.ws.client import Client
from ccxt.base.types import Int, Order, OrderBook, Str, Ticker, Trade

class bitfinex1(ccxt.async_support.bitfinex1):
    def describe(self):  # -> dict[Any, Any] | None:
        ...
    async def subscribe(self, channel, symbol, params=...): ...
    async def watch_trades(
        self, symbol: str, since: Int = ..., limit: Int = ..., params=...
    ) -> List[Trade]:
        """
        get the list of most recent trades for a particular symbol

        https://docs.bitfinex.com/v1/reference/ws-public-trades

        :param str symbol: unified symbol of the market to fetch trades for
        :param int [since]: timestamp in ms of the earliest trade to fetch
        :param int [limit]: the maximum amount of trades to fetch
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :returns dict[]: a list of `trade structures <https://docs.ccxt.com/#/?id=public-trades>`
        """
        ...

    async def watch_ticker(self, symbol: str, params=...) -> Ticker:
        """
        watches a price ticker, a statistical calculation with the information calculated over the past 24 hours for a specific market

        https://docs.bitfinex.com/v1/reference/ws-public-ticker

        :param str symbol: unified symbol of the market to fetch the ticker for
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :returns dict: a `ticker structure <https://docs.ccxt.com/#/?id=ticker-structure>`
        """
        ...

    def handle_trades(self, client: Client, message, subscription):  # -> None:
        ...
    def parse_trade(self, trade, market=...) -> Trade: ...
    def handle_ticker(self, client: Client, message, subscription):  # -> None:
        ...
    async def watch_order_book(
        self, symbol: str, limit: Int = ..., params=...
    ) -> OrderBook:
        """
        watches information on open orders with bid(buy) and ask(sell) prices, volumes and other data

        https://docs.bitfinex.com/v1/reference/ws-public-order-books

        :param str symbol: unified symbol of the market to fetch the order book for
        :param int [limit]: the maximum amount of order book entries to return
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :returns dict: A dictionary of `order book structures <https://docs.ccxt.com/#/?id=order-book-structure>` indexed by market symbols
        """
        ...

    def handle_order_book(self, client: Client, message, subscription):  # -> None:
        ...
    def handle_heartbeat(self, client: Client, message):  # -> None:
        ...
    def handle_system_status(self, client: Client, message): ...
    def handle_subscription_status(self, client: Client, message): ...
    async def authenticate(self, params=...): ...
    def handle_authentication_message(self, client: Client, message):  # -> None:
        ...
    async def watch_order(self, id, symbol: Str = ..., params=...): ...
    async def watch_orders(
        self, symbol: Str = ..., since: Int = ..., limit: Int = ..., params=...
    ) -> List[Order]:
        """
        watches information on multiple orders made by the user

        https://docs.bitfinex.com/v1/reference/ws-auth-order-updates
        https://docs.bitfinex.com/v1/reference/ws-auth-order-snapshots

        :param str symbol: unified market symbol of the market orders were made in
        :param int [since]: the earliest time in ms to fetch orders for
        :param int [limit]: the maximum number of order structures to retrieve
        :param dict [params]: extra parameters specific to the exchange API endpoint
        :returns dict[]: a list of `order structures <https://docs.ccxt.com/#/?id=order-structure>`
        """
        ...

    def handle_orders(self, client: Client, message, subscription):  # -> None:
        ...
    def parse_ws_order_status(self, status):  # -> str | None:
        ...
    def handle_order(
        self, client: Client, order
    ):  # -> OrderedDict[Any, Any] | dict[Any, Any]:
        ...
    def handle_message(self, client: Client, message):  # -> None:
        ...
