"""
This type stub file was generated by pyright.
"""

from ccxt.binance import binance
from ccxt.abstract.binanceusdm import ImplicitAPI

class binanceusdm(binance, ImplicitAPI):
    def describe(self): # -> dict[Any, Any] | None:
        ...
    
    def transfer_in(self, code: str, amount, params=...):
        ...
    
    def transfer_out(self, code: str, amount, params=...):
        ...
    


