"""
This type stub file was generated by pyright.
"""

from ccxt.binance import binance
from ccxt.abstract.binanceus import ImplicitAPI

class binanceus(binance, ImplicitAPI):
    def describe(self): # -> dict[Any, Any] | None:
        ...
    


