"""
This type stub file was generated by pyright.
"""

from ccxt.async_support.fmfwio import fmfwio
from ccxt.abstract.bitcoincom import ImplicitAPI

class bitcoincom(fmfwio, ImplicitAPI):
    def describe(self): # -> dict[Any, Any] | None:
        ...
    


