"""
This type stub file was generated by pyright.
"""

from ccxt.coinbase import coinbase
from ccxt.abstract.coinbaseadvanced import ImplicitAPI

class coinbaseadvanced(coinbase, ImplicitAPI):
    def describe(self): # -> dict[Any, Any] | None:
        ...
    


