"""
This type stub file was generated by pyright.
"""

from ccxt.hitbtc import hitbtc
from ccxt.abstract.fmfwio import ImplicitAPI

class fmfwio(hitbtc, ImplicitAPI):
    def describe(self): # -> dict[Any, Any] | None:
        ...
    


