"""
This type stub file was generated by pyright.
"""

import orjson as orjson
from ccxt.async_support.base.ws.client import Client

orjson = ...
class AiohttpClient(Client):
    proxy = ...
    def closed(self): # -> Literal[True]:
        ...
    
    def receive(self):
        ...
    
    def handle_text_or_binary_message(self, data): # -> None:
        ...
    
    def handle_message(self, message): # -> None:
        ...
    
    def create_connection(self, session):
        ...
    
    async def send(self, message):
        ...
    
    async def close(self, code=...): # -> None:
        ...
    
    async def ping_loop(self): # -> None:
        ...
    


