"""
This type stub file was generated by pyright.
"""

from ccxt.async_support.base.ws.aiohttp_client import AiohttpClient

"""A faster version of aiohttp's websocket client that uses select and other optimizations"""

class FastClient(AiohttpClient):
    transport = ...
    def __init__(
        self,
        url,
        on_message_callback,
        on_error_callback,
        on_close_callback,
        on_connected_callback,
        config=...,
    ) -> None: ...
    def receive_loop(self):  # -> Coroutine[Any, Any, None]:
        ...
    def reset(self, error):  # -> None:
        ...
