"""
This type stub file was generated by pyright.
"""

from ccxt.abstract.fmfwio import ImplicitAPI
from ccxt.hitbtc import hitbtc

class fmfwio(hitbtc, ImplicitAPI):
    def describe(self):  # -> dict[Any, Any] | None:
        ...
