"""
This type stub file was generated by pyright.
"""

from ccxt.gate import gate
from ccxt.abstract.gateio import ImplicitAPI

class gateio(gate, ImplicitAPI):
    def describe(self): # -> dict[Any, Any] | None:
        ...
    


