"""
This type stub file was generated by pyright.
"""

from ccxt.abstract.gateio import ImplicitAPI
from ccxt.gate import gate

class gateio(gate, ImplicitAPI):
    def describe(self):  # -> dict[Any, Any] | None:
        ...
