"""
This type stub file was generated by pyright.
"""

from ccxt.htx import htx
from ccxt.abstract.huobi import ImplicitAPI

class huobi(htx, ImplicitAPI):
    def describe(self): # -> dict[Any, Any] | None:
        ...
    


