"""
This type stub file was generated by pyright.
"""

from ccxt.abstract.huobi import ImplicitAPI
from ccxt.htx import htx

class huobi(htx, ImplicitAPI):
    def describe(self):  # -> dict[Any, Any] | None:
        ...
