"""
This type stub file was generated by pyright.
"""

from ccxt.okx import okx
from ccxt.abstract.myokx import ImplicitAPI

class myokx(okx, ImplicitAPI):
    def describe(self): # -> dict[Any, Any] | None:
        ...
    


