"""
This type stub file was generated by pyright.
"""

from ccxt.async_support.onetrading import onetrading
from ccxt.abstract.bitpanda import ImplicitAPI

class bitpanda(onetrading, ImplicitAPI):
    def describe(self): # -> dict[Any, Any] | None:
        ...
    


