"""
This type stub file was generated by pyright.
"""

from functools import partial, reduce

from . import curried
from ._version import get_versions
from .dicttoolz import *
from .functoolz import *
from .itertoolz import *
from .recipes import *

sorted = ...
map = map
filter = filter
comp = ...
__version__ = ...
